---
title: "Exercises Week 11"
author: "Econometrics"
output: pdf_document
---

\begin{enumerate}

\item You are going to show that the GMM estimator is equivalent to 3SLS. That is, show that 

$$(P_WX_\bullet)^T(\Sigma^{-1}\otimes I) = X_\bullet(\Sigma^{-1}\otimes P_W),$$
where $P_WX_\bullet$ is a block-diagonal matrix with blocks given by $P_WX_i$.

Hint: Write $P_WX_\bullet$ as a Kroenecker product.

\item \textbf{Exercises 12.29-30 in ETM}: Consider the demand-supply model
	$$q_{t} = \beta_{1,1}+\beta_{2,1} x_{t2}+\beta_{3,1}x_{t3}+\gamma_{21}p_t+u_{t1},$$
	$$q_{t} = \beta_{1,2}+\beta_{4,2} x_{t4}+\beta_{5,2}x_{t5}+\gamma_{22}p_t+u_{t2},$$
	where $q_t$ is the log of quantity, $p_t$ is the log of price, $x_{t2}$ is the log of income, $x_{t3}$ is a dummy variable that accounts for regular demand shifts, and $x_{t4}$ and $x_{t5}$ are the prices of inputs. Thus the first equation is a demand function and the second equation is a supply function.
	\begin{enumerate}
	  \item For this model, precisely what is the vector $\beta_\bullet$ defined in the lecture?
	  \item How many overidentifying restrictions are there for each equation?
    \item The file $demand\_supply.csv$ contains 120 observations generated by the model. Estimate this model by 2SLS.
    \item Test the overidentifying restrictions for each equation.
    \item Now estimate the model using 3SLS. 
	\end{enumerate}
	
	\item The dataset $smoke$ in the $wooldridge$ package contains information on smoking habits and other variables for a random sample of single adults from the United States. It contains 807 observations in 10 variables:

-$educ$: years of schooling

-$cigpric$: state cig. price, cents/pack

-$white$: 1 if white

-$age$: in years

-$income$: annual income

-$cigs$: cigs. smoked per day

-$restaurn$: 1 if restaurant smk. restrictions

-$lincome$: log(income)

-$agesq$: age squared

-$lcigpric$: log(cigprice)

We use the data to estimate a demand function for daily cigarette consumption.

  \begin{enumerate}
  \item A model to estimate the effects of smoking on annual income (perhaps through lost work days due to illness, or productivity effects) is  $$log(income) = \beta_0+\beta_1 cigs+\beta_2educ+\beta_3age+\beta_4 age^2+ u_1.$$
  How do you interpret $\beta_1$?
  \item To reflect the fact that cigarette consumption might be jointly determined with income, a demand for cigarettes equation is
$$cigs =\gamma_0+\gamma_1 log(income)+\gamma_2educ+\gamma_3age+\gamma_4age^2+\gamma_5 log(cigpric)
+\gamma_6restaurn+u_2.$$
Assuming these are exogenous to the individual, what signs would you expect for $\gamma_5$ and $\gamma_6$?
\item Estimate the income equation by OLS and discuss the estimate of $\beta_1$.
\item Estimate the reduced form for $cigs$. (Recall that this entails regressing $cigs$ on all exogenous variables.) Are $log(cigpric)$ and $restaurn$ significant in the reduced form?
\item Now, estimate the income equation by 2SLS. Discuss how the estimate of $\beta_1$ compares with the OLS estimate.
\item Do you think that cigarette prices and restaurant smoking restrictions are exogenous in the income equation?
  \end{enumerate}


\end{enumerate}